# Generated by Django 4.2.5 on 2023-09-15 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                ("actor_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=45)),
                ("last_name", models.CharField(max_length=45)),
                ("last_update", models.DateField(auto_now=True)),
            ],
            options={
                "db_table": "actor",
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                ("address_id", models.AutoField(primary_key=True, serialize=False)),
                ("address", models.CharField(max_length=50)),
                ("address2", models.CharField(blank=True, max_length=50, null=True)),
                ("district", models.CharField(max_length=20)),
                ("postal_code", models.CharField(blank=True, max_length=10, null=True)),
                ("phone", models.CharField(max_length=20)),
                ("last_update", models.DateField(auto_now=True)),
            ],
            options={
                "db_table": "address",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=25)),
                ("last_update", models.DateField(auto_now=True)),
            ],
            options={
                "db_table": "category",
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                ("country_id", models.AutoField(primary_key=True, serialize=False)),
                ("country", models.CharField(max_length=50)),
                ("last_update", models.DateField(auto_now=True, null=True)),
            ],
            options={
                "db_table": "country",
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("customer_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=45)),
                ("last_name", models.CharField(max_length=45)),
                ("email", models.CharField(blank=True, max_length=50, null=True)),
                ("active", models.CharField(max_length=1)),
                ("create_date", models.DateField(auto_now_add=True)),
                ("last_update", models.DateField(auto_now=True)),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="renta.address"
                    ),
                ),
            ],
            options={
                "db_table": "customer",
            },
        ),
        migrations.CreateModel(
            name="Film",
            fields=[
                ("film_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("release_year", models.CharField(blank=True, max_length=4, null=True)),
                ("rental_duration", models.SmallIntegerField()),
                ("rental_rate", models.DecimalField(decimal_places=5, max_digits=10)),
                ("length", models.SmallIntegerField(blank=True, null=True)),
                (
                    "replacement_cost",
                    models.DecimalField(decimal_places=5, max_digits=10),
                ),
                ("rating", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "special_features",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_update", models.DateField(auto_now=True)),
            ],
            options={
                "db_table": "film",
            },
        ),
        migrations.CreateModel(
            name="FilmText",
            fields=[
                ("film_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "film_text",
            },
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                ("inventory_id", models.AutoField(primary_key=True, serialize=False)),
                ("last_update", models.DateField(auto_now=True)),
                (
                    "film",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="renta.film"
                    ),
                ),
            ],
            options={
                "db_table": "inventory",
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                ("language_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
                ("last_update", models.DateField(auto_now=True)),
            ],
            options={
                "db_table": "language",
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                ("staff_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=45)),
                ("last_name", models.CharField(max_length=45)),
                ("picture", models.BinaryField(blank=True, null=True)),
                ("email", models.CharField(blank=True, max_length=50, null=True)),
                ("active", models.SmallIntegerField()),
                ("username", models.CharField(max_length=16)),
                ("password", models.CharField(blank=True, max_length=40, null=True)),
                ("last_update", models.DateField(auto_now=True)),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="renta.address"
                    ),
                ),
            ],
            options={
                "db_table": "staff",
            },
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                ("store_id", models.AutoField(primary_key=True, serialize=False)),
                ("last_update", models.DateField(auto_now=True)),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="renta.address"
                    ),
                ),
                (
                    "manager_staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="manager_staff_1",
                        to="renta.staff",
                    ),
                ),
            ],
            options={
                "db_table": "store",
            },
        ),
        migrations.AddField(
            model_name="staff",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="renta.store"
            ),
        ),
        migrations.CreateModel(
            name="Rental",
            fields=[
                ("rental_id", models.AutoField(primary_key=True, serialize=False)),
                ("rental_date", models.DateField()),
                ("return_date", models.DateField(blank=True, null=True)),
                ("last_update", models.DateField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="renta.customer",
                    ),
                ),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="renta.inventory",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="renta.staff"
                    ),
                ),
            ],
            options={
                "db_table": "rental",
                "unique_together": {("rental_date", "inventory", "customer")},
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("payment_id", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_date", models.DateField()),
                ("last_update", models.DateField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="renta.customer",
                    ),
                ),
                (
                    "rental",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="renta.rental",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="renta.staff"
                    ),
                ),
            ],
            options={
                "db_table": "payment",
            },
        ),
        migrations.AddField(
            model_name="inventory",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="renta.store"
            ),
        ),
        migrations.CreateModel(
            name="FilmActor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_update", models.DateField(auto_now=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="renta.actor"
                    ),
                ),
                (
                    "film",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="renta.film"
                    ),
                ),
            ],
            options={
                "db_table": "film_actor",
            },
        ),
        migrations.AddField(
            model_name="film",
            name="language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="renta.language"
            ),
        ),
        migrations.AddField(
            model_name="film",
            name="original_language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="film_original_language_set",
                to="renta.language",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="renta.store"
            ),
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                ("city_id", models.AutoField(primary_key=True, serialize=False)),
                ("city", models.CharField(max_length=50)),
                ("last_update", models.DateField(auto_now=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="renta.country"
                    ),
                ),
            ],
            options={
                "db_table": "city",
            },
        ),
        migrations.AddField(
            model_name="address",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="renta.city"
            ),
        ),
        migrations.CreateModel(
            name="FilmCategory",
            fields=[
                (
                    "film",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        primary_key=True,
                        serialize=False,
                        to="renta.film",
                    ),
                ),
                ("last_update", models.DateField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="renta.category",
                    ),
                ),
            ],
            options={
                "db_table": "film_category",
            },
        ),
    ]
