# Generated by Django 4.2.5 on 2023-09-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("renta", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actor",
            name="actor_id",
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="address",
            name="address_id",
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="category",
            name="category_id",
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="city",
            name="city_id",
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="country",
            name="country_id",
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="customer",
            name="customer_id",
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="film",
            name="film_id",
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="filmtext",
            name="film_id",
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="inventory_id",
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="language",
            name="language_id",
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_id",
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="rental",
            name="rental_id",
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="staff",
            name="staff_id",
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="store",
            name="store_id",
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
