# Generated by Django 4.2.5 on 2023-09-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("renta", "0002_alter_actor_actor_id_alter_address_address_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actor",
            name="last_update",
            field=models.DateField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="last_update",
            field=models.DateField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="last_update",
            field=models.DateField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="city",
            name="last_update",
            field=models.DateField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="last_update",
            field=models.DateField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="create_date",
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="last_update",
            field=models.DateField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="film",
            name="last_update",
            field=models.DateField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="filmactor",
            name="last_update",
            field=models.DateField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="filmcategory",
            name="last_update",
            field=models.DateField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="last_update",
            field=models.DateField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="language",
            name="last_update",
            field=models.DateField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="last_update",
            field=models.DateField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="rental",
            name="last_update",
            field=models.DateField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="rental",
            name="rental_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="rental",
            name="return_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="staff",
            name="last_update",
            field=models.DateField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="store",
            name="last_update",
            field=models.DateField(auto_now=True, db_index=True),
        ),
    ]
