# Generated by Django 4.2.5 on 2023-10-02 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('renta', '0003_alter_actor_last_update_alter_address_last_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='category_film', to='renta.category'),
        ),
        migrations.AlterField(
            model_name='filmcategory',
            name='film',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, related_name='film_category', serialize=False, to='renta.film'),
        ),
    ]