#/bin/bash

GeneraSVG(){
TYPE=svg

nombreArchivo=$1

dot $nombreArchivo.gv -T$TYPE -o Generados/$nombreArchivo.$TYPE
#inkscape -z -f Generados/$nombreArchivo.$TYPE --export-latex --export-pdf="Generados/$nombreArchivo.pdf"
#mv Generados/$nombreArchivo.pdf_tex Generados/$nombreArchivo.tex
#rm Generados/$nombreArchivo.pdf
}

GeneraPNG(){
TYPE=png
nombreArchivo=$1
dot $nombreArchivo.gv -T$TYPE -o Generados/$nombreArchivo.$TYPE
}

GeneraTex(){
  ## --use-part-section

  nombreArchivo=$1
  idioma=es
  generadoPor='/^Generated by \\href{/d'
  tipoDocumento=article
  tamPapel=letterpaper
  tamLetra=11pt
  opcionesDoc=$tamPapel,$tamLetra
  plantilla=latex2e/xelatex.tex
  OPCIONES="--template=$plantilla --documentclass=$tipoDocumento --documentoptions=$opcionesDoc --section-subtitles -r 5 -l $idioma"
  rst2xetex $OPCIONES $nombreArchivo.rst $nombreArchivo.tex > $nombreArchivo.rst.log
  sed -i 's/.svg/.eps/g'  $nombreArchivo.tex
  #sed -i 's/\\DUroletitlereference}\[1\]{\\textsl{#1}}/\\DUroletitlereference}[1]{\\ref{#1}}/g' $nombreArchivo.tex
  sed -i 's/|,|/}{/g' $nombreArchivo.tex
  #sed -i 's/{[ ]*/{/g' $nombreArchivo.tex
  #sed -i 's/[ ]*}/}/g' $nombreArchivo.tex
  #sed -i 's/\DUrole{imagentex}/\imagentex/g' $nombreArchivo.tex

  #sed -i 's/\\begin{document}/\\title{Mejoramiento del Proceso de deshidratación mediante la construcción de un sistema de control automático}\n\\author{Daniel Rodrigo Saguez Tezanos Pinto}\n\\date{Diciembre, 2015}\n\\begin{document}/g' $nombreArchivo.tex
  sed -i 's/{[ ]\+/{/g' $nombreArchivo.tex
  sed -i 's/[ ]\+}/}/g' $nombreArchivo.tex
  sed -i 's/... continued on next page/... Continua en la siguiente página/g' $nombreArchivo.tex
  sed -i 's/... continued/... continuación/g' $nombreArchivo.tex
#  sed -i 's/\\setcounter{secnumdepth}{0}/\\setcounter{secnumdepth}{3}/g' $nombreArchivo.tex
  GeneraPDF $nombreArchivo
}

GeneraPDF(){
  nombreArchivo=$1
  # latexmk -xelatex -d -pdflatexoption="-synctex=1 -interaction=batchmode -shell-escape" $nombreArchivo.tex
  latexmk -f -xelatex -pdf -dvi- -ps- -silent -pdflatex="xelatex %O %S -synctex=1 -interaction=nonstopmode -shell-escape" $nombreArchivo.tex
  # latexmk -c
}

nombreArchivo=NoSQL
GeneraTex $nombreArchivo
GeneraPDF $nombreArchivo

#CurrículumVítaeDsTp.tex
#nombreArchivo=CurrículumVítaeDsTp
#GeneraPDF ${nombreArchivo}

#nombreArchivo=ResumeDsTp
#GeneraPDF ${nombreArchivo}
